[tool.commitizen]
gpg_sign = true
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version = "17.25.0b1"
update_changelog_on_bump = true
version_files = [
  "java-api/setup.cfg:version",
  "java-api-stubs/pyproject.toml:version"
]
