[tool.commitizen]
gpg_sign = true
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version = "17.25.0b5"
update_changelog_on_bump = true
version_files = [
  "setup.cfg:version",
  "stubs/pyproject.toml:version"
]
