name: publish

on:
  release:
    types:
      - published

jobs:
  tox:
    uses: ./.github/workflows/tox.yml

  pypi-upload:
    needs: tox
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Upload package to PyPI
        uses: coatl-dev/actions/pypi-upload@v5
        with:
          password: ${{ secrets.PYPI_API_TOKEN_JAVA_API_PKG }}

      - name: Upload stubs to PyPI
        uses: coatl-dev/actions/pypi-upload@v5
        with:
          python-version: '3.12'
          password: ${{ secrets.PYPI_API_TOKEN_JAVA_API_STUBS }}
          working-directory: stubs
